# Домашнее задание по теме: пакеты `pandas` и `numpy` (типы данных)

## Подготовка окружения

In [1]:
# ВНИМАНИЕ: необходимо удостовериться, что виртуальная среда выбрана правильно!

!pip -V

pip 20.3.3 from /home/ira/anaconda3/envs/LevelUp_DataScience/lib/python3.8/site-packages/pip (python 3.8)


In [2]:
# !conda install pandas numpy -y

In [3]:
import numpy as np

np.__version__

'1.19.2'

In [4]:
import pandas as pd

pd.__version__



'1.2.1'

## Пакет `numpy`: типы данных

**Задача:**
- Преобразовать тип переменной `val` в другие типы (как указано в комментарии).
- Вывести результат преобразования.
- *Если результат преобразования непонятен, то разобраться самостоятельно (можно написать свои рассуждения в комментариях и преподаватель ответит при проверке) или попросить помощи у преподавателя.

**Пример:**

In [5]:
val = -1

print(f"type: {type(val)}\nvalue: {val}")

type: <class 'int'>
value: -1


In [6]:
# -> numpy.uint64
np.uint64(val)

18446744073709551615

**Задание (ДЗ):**

In [7]:
val = -129

print(f"type: {type(val)}\nvalue: {val}")

type: <class 'int'>
value: -129


In [8]:
# -> numpy.int8
np.int8(val)

127

In [9]:
# -> numpy.int16
np.int16(val)

-129

In [10]:
# -> numpy.uint8
np.uint8(val)

127

In [11]:
# -> numpy.uint32
np.uint32(val)

4294967167

In [12]:
# -> numpy.float128
np.float128(val)

-129.0

In [13]:
# -> numpy.str_
np.str_(val)

'-129'

In [14]:
# -> numpy.bool_
np.bool_(val)

True

**Задача:**
- Преобразовать тип переменной (массив) `arr` в другие типы (как указано в комментарии).
- Вывести результат преобразования.
- *Если результат преобразования непонятен, то разобраться самостоятельно (можно написать свои рассуждения в комментариях и преподаватель ответит при проверке) или попросить помощи у преподавателя.

**Пример:**

In [15]:
arr = np.array([-150, -120, 0, 120, 150])
print(f"type: {type(arr)}\nvalue: {arr}")

type: <class 'numpy.ndarray'>
value: [-150 -120    0  120  150]


In [16]:
# -> numpy.uint64
arr.astype(np.uint64)

array([18446744073709551466, 18446744073709551496,                    0,
                        120,                  150], dtype=uint64)

In [17]:
# -> numpy.int8
arr.astype(np.int8)

array([ 106, -120,    0,  120, -106], dtype=int8)

In [18]:
# -> numpy.str_
arr.astype(np.str_)

array(['-150', '-120', '0', '120', '150'], dtype='<U21')

In [19]:
# -> numpy.bool_
arr.astype(np.bool_)

array([ True,  True, False,  True,  True])

In [20]:
# -> numpy.uint8
arr.astype(np.uint8)

array([106, 136,   0, 120, 150], dtype=uint8)

## Пакет `Pandas`: типы данных

### Загрузка данных

[Источник (Hotel booking demand)](https://www.kaggle.com/jessemostipak/hotel-booking-demand)

[Описание колонок](https://www.sciencedirect.com/science/article/pii/S2352340918315191#t0005)

ВНИМАНИЕ: Предварительно датасет необходимо скачать к себе на локальный компьютер.

In [21]:
# загрузить датасет в pandas dataframe
df = pd.read_csv("./../../data/hotel_bookings.csv")

# показать все колонки
pd.options.display.max_columns = None

# вывести первые 5 и последние 5 строк
df

hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015   
1       Resort Hotel            0        737               2015   
2       Resort Hotel            0          7               2015   
3       Resort Hotel            0         13               2015   
4       Resort Hotel            0         14               2015   
...              ...          ...        ...                ...   
119385    City Hotel            0         23               2017   
119386    City Hotel            0        102               2017   
119387    City Hotel            0         34               2017   
119388    City Hotel            0        109               2017   
119389    City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
0                    July                        27   
1                    July                        27   
2                    July                        27   
3                    July                        27   
4                    July                        27   
...                   ...                       ...   
119385             August                        35   
119386             August                        35   
119387             August                        35   
119388             August                        35   
119389             August                        35   

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0   
1                               1                        0   
2                               1                        0   
3                               1                        0   
4                               1                        0   
...                           ...                      ...   
119385                         30                        2   
119386                         31                        2   
119387                         31                        2   
119388                         31                        2   
119389                         29                        2   

        stays_in_week_nights  adults  children  babies meal country  \
0                          0       2       0.0       0   BB     PRT   
1                          0       2       0.0       0   BB     PRT   
2                          1       1       0.0       0   BB     GBR   
3                          1       1       0.0       0   BB     GBR   
4                          2       2       0.0       0   BB     GBR   
...                      ...     ...       ...     ...  ...     ...   
119385                     5       2       0.0       0   BB     BEL   
119386                     5       3       0.0       0   BB     FRA   
119387                     5       2       0.0       0   BB     DEU   
119388                     5       2       0.0       0   BB     GBR   
119389                     7       2       0.0       0   HB     DEU   

       market_segment distribution_channel  is_repeated_guest  \
0              Direct               Direct                  0   
1              Direct               Direct                  0   
2              Direct               Direct                  0   
3           Corporate            Corporate                  0   
4           Online TA                TA/TO                  0   
...               ...                  ...                ...   
119385  Offline TA/TO                TA/TO                  0   
119386      Online TA                TA/TO                  0   
119387      Online TA                TA/TO                  0   
119388      Online TA                TA/TO                  0   
119389      Online TA                TA/TO                  0   

        previous_cancellations  previous_bookings_not_canceled  \
0                            0                               0   
1                            0        

In [22]:
# получить данные о датафрейме: список колонок, сколько ненулевых, типы колонок...
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

### Категориальные данные

In [23]:
# сколько байт занимает колонка meal (до преобразования)
df.meal.nbytes

955120

In [24]:
# преобразовать тип колонки meal в category
df.meal = df.meal.astype("category")

# вывести значения колонки meal
df.meal

0         BB
1         BB
2         BB
3         BB
4         BB
          ..
119385    BB
119386    BB
119387    BB
119388    BB
119389    HB
Name: meal, Length: 119390, dtype: category
Categories (5, object): ['BB', 'FB', 'HB', 'SC', 'Undefined']

In [25]:
# вывести все уникальные значения колнки meal
df.meal.unique().tolist()

['BB', 'FB', 'HB', 'SC', 'Undefined']

In [26]:
# установить порядок для категорий meal
# (['Undefined', 'SC', 'BB', 'HB', 'FB'])
df.meal.cat.set_categories(['Undefined', 'SC', 'BB', 'HB', 'FB'],
                          ordered=True)


0         BB
1         BB
2         BB
3         BB
4         BB
          ..
119385    BB
119386    BB
119387    BB
119388    BB
119389    HB
Name: meal, Length: 119390, dtype: category
Categories (5, object): ['Undefined' < 'SC' < 'BB' < 'HB' < 'FB']

In [27]:
# сколько байт занимает колонка meal (после преобразования)
df.meal.nbytes

119430

### Разреженные структуры данных

In [28]:
# сколько байт занимает колонка company (до преобразования)
df.company.nbytes

955120

In [29]:
# преобразовать тип колонки company в SparseArray
df.company = pd.Series(pd.arrays.SparseArray(df.company))

# вывести значения колонки meal
df.company

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
119385   NaN
119386   NaN
119387   NaN
119388   NaN
119389   NaN
Name: company, Length: 119390, dtype: Sparse[float64, nan]

In [30]:
# сколько байт занимает колонка company (после преобразования)
df.company.nbytes

81564

In [31]:
# плотность (% значений, которые не были "сжаты") для колонки company
df.company.sparse.density

0.056931066253455065

In [32]:
# получить данные о датафрейме (проверить, что тип колонок изменился)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype               
---  ------                          --------------   -----               
 0   hotel                           119390 non-null  object              
 1   is_canceled                     119390 non-null  int64               
 2   lead_time                       119390 non-null  int64               
 3   arrival_date_year               119390 non-null  int64               
 4   arrival_date_month              119390 non-null  object              
 5   arrival_date_week_number        119390 non-null  int64               
 6   arrival_date_day_of_month       119390 non-null  int64               
 7   stays_in_weekend_nights         119390 non-null  int64               
 8   stays_in_week_nights            119390 non-null  int64               
 9   adults                          119390 non-null  int64     

---

### Интервальный индекс

### Обработка часовых поясов

### Представление промежутка времени

### Текстовые типы данных

### Обнуляемый целочисленный тип данных

### Логические данные с пропущенными значениями