# Пакет `NumPy`: матрицы и операции над ними

---

**Источники:**

[NumPy](https://ru.wikipedia.org/wiki/NumPy)

[What is NumPy?](https://numpy.org/doc/stable/user/whatisnumpy.html)

[NumPy — Краткое руководство](https://coderlessons.com/tutorials/python-technologies/uchitsia-numpy/numpy-kratkoe-rukovodstvo)

[Матрицы. Виды матриц. Основные термины.](https://math1.ru/education/matrix/matrix.html)

[Математика. Матрицы. Введение.](https://zen.yandex.ru/media/id/5c764fc306dc8700b30ed31a/matematika-matricy-vvedenie-5cef752e3be90a00af76852b)

---

## Подготовка окружения

In [1]:
# ВНИМАНИЕ: необходимо удостовериться, что виртуальная среда выбрана правильно!

# для Linux
!which pip

# для Windows
# !pip -V

/home/ira/anaconda3/envs/LevelUp_DataScience/bin/pip


In [2]:
!conda install numpy -y

Solving environment: done

# All requested packages already installed.



In [3]:
import numpy as np

np.__version__

'1.19.2'

## Термины: матрица (matrix), вектор (vector) и скаляр (scalar)?


**Матрица** — это таблица из `m` строк и `n` столбцов.

Количество строк и столбцов задает размер матрицы. 

<img src="images/matrix_row_column_index.png"/>

<img src="images/matrix_m_n.png"/>

**Вектор (строка или столбец)**
Матрица **вектор (строка или столбец)** - это матрица записанная в виде одного столбца или одной строки.

<img src="images/vectors.png"/>

**Скаляр** - величина (возможно переменная, то есть функция), каждое значение которой может быть выражено одним числом (чаще всего подразумевается вещественное число).

##  Пакет `NumPy`

<img src="images/logo_numpy.png" height="400" width="400"/>

**`NumPy`** — библиотека с открытым исходным кодом для языка программирования Python.

**Возможности:**
- поддержка многомерных массивов (включая матрицы);
- поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.


**Назначение:**
- Математические алгоритмы, реализованные на интерпретируемых языках (например, Python), часто работают гораздо медленнее тех же алгоритмов, реализованных на компилируемых языках (например, Фортран, Си, Java).
- Библиотека `NumPy` предоставляет реализации вычислительных алгоритмов (в виде функций и операторов), оптимизированные для работы с многомерными массивами.
- В результате любой алгоритм, который может быть выражен в виде последовательности операций над массивами (матрицами) и реализованный с использованием `NumPy`, работает так же быстро, как эквивалентный код, выполняемый в `MATLAB`.


**Основным объектом `NumPy` является однородный многомерный массив (в `numpy` называется `numpy.ndarray`). Это многомерный массив элементов (обычно чисел), одного типа.**


**Наиболее важные атрибуты `ndarray`:**

- `ndarray.ndim` - число измерений (чаще их называют "оси") массива.

- `ndarray.shape` - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из `n` строк и `m` столбов, `shape` будет `(n, m)`. Число элементов кортежа `shape` равно `ndim`.

- `ndarray.size` - количество элементов массива. Равно произведению всех элементов атрибута `shape`.

- `ndarray.dtype` - объект, описывающий тип элементов массива. Можно определить `dtype`, используя стандартные типы данных Python. `NumPy` предоставляет целый список типов, как встроенных, например: `bool_`, `character`, `int8`, `int16`, `int32`, `int64`, `float8`, `float16`, `float32`, `float64`, `complex64`, `object_`, так и возможность определить собственные типы данных, в том числе и составные.

- `ndarray.itemsize` - размер каждого элемента массива в байтах.

- `ndarray.data` - буфер, содержащий фактические элементы массива. Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.

## Примеры использовать `NumPy`

### Вектор и Список

Пакет `numpy`(`np`) реализует работу с линейной алгеброй. Для создания вектора из `list` ($[1,2,3]$) с помощью np.array нужно:

In [4]:
x_vector = np.array([1,2,3])
print(x_vector)

[1 2 3]


Другой способ:

In [5]:
c_list = [1,2]
print("The list:",c_list)
print("Has length:", len(c_list))

c_vector = np.array(c_list)
print("The vector:", c_vector)
print("Has shape:",c_vector.shape)

The list: [1, 2]
Has length: 2
The vector: [1 2]
Has shape: (2,)


In [6]:
z = [5,6]
print("This is a list, not an array:",z)
print(type(z))

This is a list, not an array: [5, 6]
<class 'list'>


In [7]:
zarray = np.array(z)
print("This is an array, not a list",zarray)
print(type(zarray))

This is an array, not a list [5 6]
<class 'numpy.ndarray'>


### Матрицы

In [8]:
b = list(zip(z,c_vector))
print(b)
print("Note that the length of our zipped list is 2 not (2 by 2):",len(b))

[(5, 1), (6, 2)]
Note that the length of our zipped list is 2 not (2 by 2): 2


In [9]:
print("But we can convert the list to a matrix like this:")
A = np.array(b)
print(A)
print(type(A))
print("A has shape:",A.shape)

But we can convert the list to a matrix like this:
[[5 1]
 [6 2]]
<class 'numpy.ndarray'>
A has shape: (2, 2)


## Операции с матрицами

### Сложение / вычитание скалярной величины (числа)

Рассмотрим пример для размерности $2 \times 2$, где количество строк $\times$ количество колонок.

$A$=$\begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix}$.


Скаляром обозначим $S$.
$$
\begin{equation}
	A+S=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}+S
	=\begin{bmatrix}
	  a_{11}+S & a_{12}+S \\
	  a_{21}+S & a_{22}+S 	
	\end{bmatrix}
\end{equation}
$$

Аналогично: 

$$
\begin{equation}
	A-S=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}-S
	=\begin{bmatrix}
	  a_{11}-S & a_{12}-S \\
	  a_{21}-S & a_{22}-S 	
	\end{bmatrix}
\end{equation}
$$


Это правило работает для любой размерности.

In [10]:
print('A:\n', A, '\n')

result = A + 3
#or
result = 3 + A
print('result:\n', result)

A:
 [[5 1]
 [6 2]] 

result:
 [[8 4]
 [9 5]]


### Сложение и вычитание матриц

$A$=$\bigl( \begin{smallmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{smallmatrix} \bigr)$

$B$=$\bigl( \begin{smallmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{smallmatrix} \bigr)$.

\begin{equation}
	A -B =
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix} -
	\begin{bmatrix} b_{11} & b_{12} \\
	  b_{21} & b_{22}
	\end{bmatrix}
	=
	\begin{bmatrix}
	  a_{11}-b_{11} & a_{12}-b_{12} \\
	  a_{21}-b_{21} & a_{22}-b_{22} 	
	\end{bmatrix}
\end{equation}

Аналогично:

\begin{equation}
	A + B =
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix} +
	\begin{bmatrix} b_{11} & b_{12} \\
	  b_{21} & b_{22}
	\end{bmatrix}
	=
	\begin{bmatrix}
	  a_{11}+b_{11} & a_{12}+b_{12} \\
	  a_{21}+b_{21} & a_{22}+b_{22} 	
	\end{bmatrix}
\end{equation}


Важно помнить, что при сложении / вычитании размерность матриц должна быть одинаковой и не изменяется.

\begin{equation}
A_{2 \times 2} + B_{2 \times 2}= \begin{bmatrix}
  a_{11}+b_{11} & a_{12}+b_{12} \\
  a_{21}+b_{21} & a_{22}+b_{22} 	
\end{bmatrix}_{2 \times 2}
\end{equation}

In [11]:
B = np.random.randn(2,2)
print(A)
print(B)

[[5 1]
 [6 2]]
[[ 0.96151073  0.56983092]
 [-1.36655144 -0.54673174]]


In [12]:
result = A + B
result

array([[5.96151073, 1.56983092],
       [4.63344856, 1.45326826]])

## Умножение матриц

### Умножение матриц на скаляр (число)

$A$=$\bigl( \begin{smallmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{smallmatrix} \bigr)$.
Обозначим скаляром $S$

\begin{equation}
	S \times A = S \times \begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}
	=
	\begin{bmatrix}
	  Sa_{11} & Sa_{12} \\
	  Sa_{21} & Sa_{22} 	
	\end{bmatrix}
\end{equation}

$3 \times A$=$A \times 3$


In [13]:
A * 3

array([[15,  3],
       [18,  6]])

### Умножение матриц

$2 \times 1$ вектор $C=\bigl( \begin{smallmatrix} c_{11} \\
  c_{21}
\end{smallmatrix} \bigr)$  

Умножим матрицу $A_{2 \times 2}$ и вектор $C_{2 \times 1}$. 
В данном случае обязательно должны совпадать размерности column (левой) **and** row (правой).


\begin{equation}
	A_{2 \times 2} \times C_{2 \times 1} = 
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}_{2 \times 2}
    \times
    \begin{bmatrix}
	c_{11} \\
	c_{21}
	\end{bmatrix}_{2 \times 1}
	=
	\begin{bmatrix}
	  a_{11}c_{11} + a_{12}c_{21} \\
	  a_{21}c_{11} + a_{22}c_{21} 	
	\end{bmatrix}_{2 \times 1}
\end{equation}

Матрица C с размерностями $2 \times 3$ и матрица A с размерностями $3 \times 2$

\begin{equation}
	A_{3 \times 2}=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} \\
	  a_{31} & a_{32} 	
	\end{bmatrix}_{3 \times 2}
	,
	C_{2 \times 3} = 
	\begin{bmatrix}
		  c_{11} & c_{12} & c_{13} \\
		  c_{21} & c_{22} & c_{23} \\
	\end{bmatrix}_{2 \times 3}
	\end{equation}

A $\times$ C будет

\begin{align}
	A_{3 \times 2} \times C_{2 \times 3}=&
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} \\
	  a_{31} & a_{32} 	
	\end{bmatrix}_{3 \times 2}
	\times
	\begin{bmatrix}
	  c_{11} & c_{12} & c_{13} \\
	  c_{21} & c_{22} & c_{23} 
	\end{bmatrix}_{2 \times 3} \\
	=&
	\begin{bmatrix}
	  a_{11} c_{11}+a_{12} c_{21} & a_{11} c_{12}+a_{12} c_{22} & a_{11} c_{13}+a_{12} c_{23} \\
	  a_{21} c_{11}+a_{22} c_{21} & a_{21} c_{12}+a_{22} c_{22} & a_{21} c_{13}+a_{22} c_{23} \\
	  a_{31} c_{11}+a_{32} c_{21} & a_{31} c_{12}+a_{32} c_{22} & a_{31} c_{13}+a_{32} c_{23}
	\end{bmatrix}_{3 \times 3}	
\end{align}

$X_{r_x \times c_x} \times Y_{r_y \times c_y}$

Важно:

* $c_x=r_y$, columns первого операнда дожны быть равны rows второго операнда.
* Размерность результата будет равна $r_x \times c_y$ (rows первого операнда и columns второго операнда).

Следовательно, $X \times Y = Y \times X$ истинно **НЕ** во всех случаях.

[Wiki Matrix multiplication](http://en.wikipedia.org/wiki/Matrix_multiplication)

In [14]:
# Let's redefine A and C to demonstrate matrix multiplication:
A = np.arange(6).reshape((3,2))
C = np.random.randn(2,2)

print(A.shape)
print(C.shape)

(3, 2)
(2, 2)


Это также называется Скалярное произведение матриц (`dot`):

In [15]:
print(A.dot(C))
print(np.dot(A,C))

[[ -1.35974725  -1.45135186]
 [ -4.86463409  -7.04515265]
 [ -8.36952093 -12.63895344]]
[[ -1.35974725  -1.45135186]
 [ -4.86463409  -7.04515265]
 [ -8.36952093 -12.63895344]]


А так не сработает из-за размерностей:

In [16]:
# C.dot(A)

## Обратная матрица

Матрица $2 \times 2$ $A$=$\bigl( \begin{smallmatrix} a_{11} & a_{12} \\ a_{21} & a_{22}\end{smallmatrix} \bigr)$.
Обозначим обратную матрицу для $A$ как $A^{-1}$)

$$
\begin{equation}
	A^{-1}=\begin{bmatrix}
             a_{11} & a_{12} \\
		     a_{21} & a_{22} 
           \end{bmatrix}^{-1}=\frac{1}{a_{11}a_{22}-a_{12}a_{21}}	\begin{bmatrix}
		             a_{22} & -a_{12} \\
				     -a_{21} & a_{11} 
		           \end{bmatrix}
\end{equation}
$$

Обратная матрица $A^{-1}$ имеет полезное свойсво:
$$
\begin{equation}
	A \times A^{-1}=A^{-1} \times A=I
\end{equation}
$$

где I, единичная матрица (как скалярная 1)

$$
\begin{equation}
	I_{2 \times 2}=\begin{bmatrix}
             1 & 0 \\
		     0 & 1 
           \end{bmatrix}
\end{equation}
$$
более того, $A \times I = A$ и $I \times A = A$.

[Wiki Matrix inversion](http://en.wikipedia.org/wiki/Matrix_inversion)

In [17]:
# note, we need a square matrix (# rows = # cols), use C:
C_inverse = np.linalg.inv(C)
print(C_inverse)

[[ 1.15217232 -1.06817915]
 [-1.07945095  0.31174636]]


Check that $C\times C^{-1} = I$:

In [18]:
print(C.dot(C_inverse))
print("Is identical to:")
print(C_inverse.dot(C))

[[1. 0.]
 [0. 1.]]
Is identical to:
[[1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00]]


## Транспонирование матриц

$$
\begin{equation}
	A_{3 \times 2}=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} \\
	  a_{31} & a_{32} 	
	\end{bmatrix}_{3 \times 2}	
\end{equation}
$$
Транспонированная матрица A (обозначается как $A^{\prime}$)
$$
\begin{equation}
   A^{\prime}=\begin{bmatrix}
	  a_{11} & a_{21} & a_{31} \\
	  a_{12} & a_{22} & a_{32} \\
	\end{bmatrix}_{2 \times 3}
\end{equation}
$$

In [19]:
A = np.arange(6).reshape((3,2))
B = np.arange(8).reshape((2,4))
print("A is")
print(A)

print("The Transpose of A is")
print(A.T)

A is
[[0 1]
 [2 3]
 [4 5]]
The Transpose of A is
[[0 2 4]
 [1 3 5]]


Матрица A размерности $N \times M$ и B размерности $M \times P$
$$
\begin{equation}
	(AB)^{\prime}=B^{\prime}A^{\prime}
\end{equation}
$$

[Wiki Matrix transposition](http://en.wikipedia.org/wiki/Matrix_transposition)

In [20]:
print(B.T.dot(A.T))
print("Is identical to:")
print((A.dot(B)).T)

[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]
Is identical to:
[[ 4 12 20]
 [ 5 17 29]
 [ 6 22 38]
 [ 7 27 47]]
