# Домашнее задание по теме: пакеты `pandas` и `numpy` (типы данных)

## Подготовка окружения

In [1]:
# ВНИМАНИЕ: необходимо удостовериться, что виртуальная среда выбрана правильно!

!pip -V

pip 20.3.3 from /home/ira/anaconda3/envs/LevelUp_DataScience/lib/python3.8/site-packages/pip (python 3.8)


In [2]:
# !conda install pandas numpy -y

In [3]:
import datetime

In [4]:
import numpy as np

np.__version__

'1.19.2'

In [5]:
import pandas as pd

pd.__version__

'1.2.2'

## Пакет `numpy`: типы данных

**Задача:**
- Преобразовать тип переменной `val` в другие типы (как указано в комментарии).
- Вывести результат преобразования.
- *Если результат преобразования непонятен, то разобраться самостоятельно (можно написать свои рассуждения в комментариях и преподаватель ответит при проверке) или попросить помощи у преподавателя.

**Пример:**

In [6]:
val = -1

print(f"type: {type(val)}\nvalue: {val}")

type: <class 'int'>
value: -1


In [7]:
# -> numpy.uint64
np.uint64(val)

18446744073709551615

**Задание (ДЗ):**

In [8]:
val = -129

print(f"type: {type(val)}\nvalue: {val}")

type: <class 'int'>
value: -129


In [9]:
# -> numpy.int8
np.int8(val)

127

In [10]:
# -> numpy.int16
np.int16(val)

-129

In [11]:
# -> numpy.uint8
np.uint8(val)

127

In [12]:
# -> numpy.uint32
np.uint32(val)

4294967167

In [13]:
# -> numpy.float64
np.float64(val)

-129.0

In [14]:
# -> numpy.str_
np.str_(val)

'-129'

In [15]:
# -> numpy.bool_
np.bool_(val)

True

**Задача:**
- Преобразовать тип переменной (массив) `arr` в другие типы (как указано в комментарии).
- Вывести результат преобразования.
- *Если результат преобразования непонятен, то разобраться самостоятельно (можно написать свои рассуждения в комментариях и преподаватель ответит при проверке) или попросить помощи у преподавателя.

**Пример:**

In [16]:
arr = np.array([-150, -120, 0, 120, 150])
print(f"type: {type(arr)}\nvalue: {arr}")

type: <class 'numpy.ndarray'>
value: [-150 -120    0  120  150]


In [17]:
# -> numpy.uint64
arr.astype(np.uint64)

array([18446744073709551466, 18446744073709551496,                    0,
                        120,                  150], dtype=uint64)

**Задание (ДЗ):**

In [18]:
# -> numpy.int8
arr.astype(np.int8)

array([ 106, -120,    0,  120, -106], dtype=int8)

In [19]:
# -> numpy.str_
arr.astype(np.str_)

array(['-150', '-120', '0', '120', '150'], dtype='<U21')

In [20]:
# -> numpy.bool_
arr.astype(np.bool_)

array([ True,  True, False,  True,  True])

In [21]:
# -> numpy.uint8
arr.astype(np.uint8)

array([106, 136,   0, 120, 150], dtype=uint8)

## Пакет `Pandas`: типы данных

### Загрузка данных (Hotel booking demand)

[Источник (Hotel booking demand)](https://www.kaggle.com/jessemostipak/hotel-booking-demand)

[Описание колонок](https://www.sciencedirect.com/science/article/pii/S2352340918315191#t0005)

ВНИМАНИЕ: Предварительно датасет необходимо скачать к себе на локальный компьютер.

In [22]:
# показать все столбцы
pd.options.display.max_columns = None

# загрузить датасет в pandas dataframe
df = pd.read_csv("./../../data/hotel_bookings.csv")

# вывести первые 5 и последние 5 строк
df

hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015   
1       Resort Hotel            0        737               2015   
2       Resort Hotel            0          7               2015   
3       Resort Hotel            0         13               2015   
4       Resort Hotel            0         14               2015   
...              ...          ...        ...                ...   
119385    City Hotel            0         23               2017   
119386    City Hotel            0        102               2017   
119387    City Hotel            0         34               2017   
119388    City Hotel            0        109               2017   
119389    City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
0                    July                        27   
1                    July                        27   
2                    July                        27   
3                    July                        27   
4                    July                        27   
...                   ...                       ...   
119385             August                        35   
119386             August                        35   
119387             August                        35   
119388             August                        35   
119389             August                        35   

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0   
1                               1                        0   
2                               1                        0   
3                               1                        0   
4                               1                        0   
...                           ...                      ...   
119385                         30                        2   
119386                         31                        2   
119387                         31                        2   
119388                         31                        2   
119389                         29                        2   

        stays_in_week_nights  adults  children  babies meal country  \
0                          0       2       0.0       0   BB     PRT   
1                          0       2       0.0       0   BB     PRT   
2                          1       1       0.0       0   BB     GBR   
3                          1       1       0.0       0   BB     GBR   
4                          2       2       0.0       0   BB     GBR   
...                      ...     ...       ...     ...  ...     ...   
119385                     5       2       0.0       0   BB     BEL   
119386                     5       3       0.0       0   BB     FRA   
119387                     5       2       0.0       0   BB     DEU   
119388                     5       2       0.0       0   BB     GBR   
119389                     7       2       0.0       0   HB     DEU   

       market_segment distribution_channel  is_repeated_guest  \
0              Direct               Direct                  0   
1              Direct               Direct                  0   
2              Direct               Direct                  0   
3           Corporate            Corporate                  0   
4           Online TA                TA/TO                  0   
...               ...                  ...                ...   
119385  Offline TA/TO                TA/TO                  0   
119386      Online TA                TA/TO                  0   
119387      Online TA                TA/TO                  0   
119388      Online TA                TA/TO                  0   
119389      Online TA                TA/TO                  0   

        previous_cancellations  previous_bookings_not_canceled  \
0                            0                               0   
1                            0        

In [23]:
# получить данные о датафрейме: список колонок, сколько ненулевых, типы колонок...
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

### Категориальные данные

In [24]:
# сколько байт занимает столбец meal (до преобразования)
df.meal.nbytes

955120

In [25]:
# преобразовать тип столбца meal в category
df.meal = df.meal.astype("category")

# вывести значения столбца meal
df.meal

0         BB
1         BB
2         BB
3         BB
4         BB
          ..
119385    BB
119386    BB
119387    BB
119388    BB
119389    HB
Name: meal, Length: 119390, dtype: category
Categories (5, object): ['BB', 'FB', 'HB', 'SC', 'Undefined']

In [26]:
# вывести все уникальные значения колнки meal (тип list)
df.meal.unique().tolist()

['BB', 'FB', 'HB', 'SC', 'Undefined']

In [27]:
# установить порядок для категорий meal
# (['Undefined', 'SC', 'BB', 'HB', 'FB'])
df.meal.cat.set_categories(['Undefined', 'SC', 'BB', 'HB', 'FB'],
                          ordered=True)


0         BB
1         BB
2         BB
3         BB
4         BB
          ..
119385    BB
119386    BB
119387    BB
119388    BB
119389    HB
Name: meal, Length: 119390, dtype: category
Categories (5, object): ['Undefined' < 'SC' < 'BB' < 'HB' < 'FB']

In [28]:
# сколько байт занимает столбец meal (после преобразования)
df.meal.nbytes

119430

### Разреженные структуры данных

In [29]:
# сколько байт занимает столбец company (до преобразования)
df.company.nbytes

955120

In [30]:
# преобразовать тип столбца company в SparseArray
df.company = pd.Series(pd.arrays.SparseArray(df.company))

# вывести значения столбца meal
df.company

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
119385   NaN
119386   NaN
119387   NaN
119388   NaN
119389   NaN
Name: company, Length: 119390, dtype: Sparse[float64, nan]

In [31]:
# сколько байт занимает столбец company (после преобразования)
df.company.nbytes

81564

In [32]:
# плотность (% значений, которые не были "сжаты") для столбца company
df.company.sparse.density

0.056931066253455065

In [33]:
# получить данные о датафрейме (проверить, что тип колонок изменился)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype               
---  ------                          --------------   -----               
 0   hotel                           119390 non-null  object              
 1   is_canceled                     119390 non-null  int64               
 2   lead_time                       119390 non-null  int64               
 3   arrival_date_year               119390 non-null  int64               
 4   arrival_date_month              119390 non-null  object              
 5   arrival_date_week_number        119390 non-null  int64               
 6   arrival_date_day_of_month       119390 non-null  int64               
 7   stays_in_weekend_nights         119390 non-null  int64               
 8   stays_in_week_nights            119390 non-null  int64               
 9   adults                          119390 non-null  int64     

### Интервальный индекс

In [34]:
# вывести все уникальные значения столбца lead_time
df.lead_time.unique()

array([342, 737,   7,  13,  14,   0,   9,  85,  75,  23,  35,  68,  18,
        37,  12,  72, 127,  78,  48,  60,  77,  99, 118,  95,  96,  69,
        45,  40,  15,  36,  43,  70,  16, 107,  47, 113,  90,  50,  93,
        76,   3,   1,  10,   5,  17,  51,  71,  63,  62, 101,   2,  81,
       368, 364, 324,  79,  21, 109, 102,   4,  98,  92,  26,  73, 115,
        86,  52,  29,  30,  33,  32,   8, 100,  44,  80,  97,  64,  39,
        34,  27,  82,  94, 110, 111,  84,  66, 104,  28, 258, 112,  65,
        67,  55,  88,  54, 292,  83, 105, 280, 394,  24, 103, 366, 249,
        22,  91,  11, 108, 106,  31,  87,  41, 304, 117,  59,  53,  58,
       116,  42, 321,  38,  56,  49, 317,   6,  57,  19,  25, 315, 123,
        46,  89,  61, 312, 299, 130,  74, 298, 119,  20, 286, 136, 129,
       124, 327, 131, 460, 140, 114, 139, 122, 137, 126, 120, 128, 135,
       150, 143, 151, 132, 125, 157, 147, 138, 156, 164, 346, 159, 160,
       161, 333, 381, 149, 154, 297, 163, 314, 155, 323, 340, 35

In [35]:
# вывести минимальное значение столбца lead_time
df.lead_time.min()

0

In [36]:
# вывести максимальное значение столбца lead_time
df.lead_time.max()

737

In [37]:
# используя функцию qcut разбить значения в стобце lead_time на 4 квантили
lead_time_intervals = pd.qcut(df.lead_time.unique(), q = 4)

# вывести результат
lead_time_intervals

[(239.0, 358.5], (358.5, 737.0], (-0.001, 119.5], (-0.001, 119.5], (-0.001, 119.5], ..., (358.5, 737.0], (358.5, 737.0], (358.5, 737.0], (358.5, 737.0], (358.5, 737.0]]
Length: 479
Categories (4, interval[float64]): [(-0.001, 119.5] < (119.5, 239.0] < (239.0, 358.5] < (358.5, 737.0]]

In [38]:
# получить тип результата функции qcut
type(lead_time_intervals)

pandas.core.arrays.categorical.Categorical

In [39]:
# получить список категории
lead_time_intervals.categories

IntervalIndex([(-0.001, 119.5], (119.5, 239.0], (239.0, 358.5], (358.5, 737.0]],
              closed='right',
              dtype='interval[float64]')

In [40]:
# число вхождений в каждый бин (интевал)
pd.value_counts(lead_time_intervals)

(-0.001, 119.5]    120
(119.5, 239.0]     120
(358.5, 737.0]     120
(239.0, 358.5]     119
dtype: int64

### Обработка часовых поясов

In [41]:
# вывести значения столбца reservation_status_date
# обратить внимание на dtype
df.reservation_status_date

0         2015-07-01
1         2015-07-01
2         2015-07-02
3         2015-07-02
4         2015-07-03
             ...    
119385    2017-09-06
119386    2017-09-07
119387    2017-09-07
119388    2017-09-07
119389    2017-09-07
Name: reservation_status_date, Length: 119390, dtype: object

In [42]:
# конвертировать тип столбца reservation_status_date (object -> datetime64)
df.reservation_status_date = pd.to_datetime(df.reservation_status_date)

In [43]:
# вывести значения столбца reservation_status_date
# обратить внимание на dtype
df.reservation_status_date

0        2015-07-01
1        2015-07-01
2        2015-07-02
3        2015-07-02
4        2015-07-03
            ...    
119385   2017-09-06
119386   2017-09-07
119387   2017-09-07
119388   2017-09-07
119389   2017-09-07
Name: reservation_status_date, Length: 119390, dtype: datetime64[ns]

In [44]:
# установить стандарт UTC для столбца reservation_status_date
# обратить внимание на dtype
df.reservation_status_date = df.reservation_status_date.dt.tz_localize("UTC")

# отобразить столбец reservation_status_date
df.reservation_status_date

0        2015-07-01 00:00:00+00:00
1        2015-07-01 00:00:00+00:00
2        2015-07-02 00:00:00+00:00
3        2015-07-02 00:00:00+00:00
4        2015-07-03 00:00:00+00:00
                    ...           
119385   2017-09-06 00:00:00+00:00
119386   2017-09-07 00:00:00+00:00
119387   2017-09-07 00:00:00+00:00
119388   2017-09-07 00:00:00+00:00
119389   2017-09-07 00:00:00+00:00
Name: reservation_status_date, Length: 119390, dtype: datetime64[ns, UTC]

In [45]:
# изменить часовой пояс столбца reservation_status_date на "Africa/Lome"
# обратить внимание на dtype
df.reservation_status_date = df.reservation_status_date.dt.tz_convert("Africa/Lome")

# отобразить столбец reservation_status_date
df.reservation_status_date

0        2015-07-01 00:00:00+00:00
1        2015-07-01 00:00:00+00:00
2        2015-07-02 00:00:00+00:00
3        2015-07-02 00:00:00+00:00
4        2015-07-03 00:00:00+00:00
                    ...           
119385   2017-09-06 00:00:00+00:00
119386   2017-09-07 00:00:00+00:00
119387   2017-09-07 00:00:00+00:00
119388   2017-09-07 00:00:00+00:00
119389   2017-09-07 00:00:00+00:00
Name: reservation_status_date, Length: 119390, dtype: datetime64[ns, Africa/Lome]

In [46]:
# добавить к каждой дате столбца reservation_status_date 30 дней и 5 часов
df.reservation_status_date + pd.Timedelta("30 day 5 hours")

0        2015-07-31 05:00:00+00:00
1        2015-07-31 05:00:00+00:00
2        2015-08-01 05:00:00+00:00
3        2015-08-01 05:00:00+00:00
4        2015-08-02 05:00:00+00:00
                    ...           
119385   2017-10-06 05:00:00+00:00
119386   2017-10-07 05:00:00+00:00
119387   2017-10-07 05:00:00+00:00
119388   2017-10-07 05:00:00+00:00
119389   2017-10-07 05:00:00+00:00
Name: reservation_status_date, Length: 119390, dtype: datetime64[ns, Africa/Lome]

### Представление промежутка времени

In [47]:
# добавить столбец reservation_status_date_period datetime64 -> period[min]
# UserWarning: Converting to PeriodArray/Index representation will drop timezone information. - это норма :)
df["reservation_status_date_period"] = df.reservation_status_date.dt.to_period('min')

# отобразить столбец reservation_status_date_period
df.reservation_status_date_period

/home/ira/anaconda3/envs/LevelUp_DataScience/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py:1101: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  warnings.warn(


0         2015-07-01 00:00
1         2015-07-01 00:00
2         2015-07-02 00:00
3         2015-07-02 00:00
4         2015-07-03 00:00
                ...       
119385    2017-09-06 00:00
119386    2017-09-07 00:00
119387    2017-09-07 00:00
119388    2017-09-07 00:00
119389    2017-09-07 00:00
Name: reservation_status_date_period, Length: 119390, dtype: period[T]

In [48]:
# обавить 4 часа к каждому элементу столбца reservation_status_date_period
df.reservation_status_date_period = df.reservation_status_date_period + 4

# отобразить столбец reservation_status_date_period
df.reservation_status_date_period

0         2015-07-01 00:04
1         2015-07-01 00:04
2         2015-07-02 00:04
3         2015-07-02 00:04
4         2015-07-03 00:04
                ...       
119385    2017-09-06 00:04
119386    2017-09-07 00:04
119387    2017-09-07 00:04
119388    2017-09-07 00:04
119389    2017-09-07 00:04
Name: reservation_status_date_period, Length: 119390, dtype: period[T]

In [49]:
# обавить timedelta равную 55 минут к каждому элементу столбца reservation_status_date_period
df.reservation_status_date_period = df.reservation_status_date_period + datetime.timedelta(minutes=55)

# отобразить столбец reservation_status_date_period
df.reservation_status_date_period

0         2015-07-01 00:59
1         2015-07-01 00:59
2         2015-07-02 00:59
3         2015-07-02 00:59
4         2015-07-03 00:59
                ...       
119385    2017-09-06 00:59
119386    2017-09-07 00:59
119387    2017-09-07 00:59
119388    2017-09-07 00:59
119389    2017-09-07 00:59
Name: reservation_status_date_period, Length: 119390, dtype: period[T]

### Обнуляемый целочисленный тип данных

In [50]:
# TODO

### Логические данные с пропущенными значениями

In [51]:
# TODO

### Текстовые типы данных

In [52]:
# TODO