# `NumPy`: матрицы и операции над ними

### Загрузка библиотеки `numpy`


In [1]:
import numpy as np

#### Вектор и Список

Пакет `numpy`(`np`) реализует работу с линейной алгеброй. Для создания вектора из list ($[1,2,3]$) с помощью np.array нужно:

In [2]:
x_vector = np.array([1,2,3])
print(x_vector)

[1 2 3]


Другой способ:

In [3]:
c_list = [1,2]
print("The list:",c_list)
print("Has length:", len(c_list))

c_vector = np.array(c_list)
print("The vector:", c_vector)
print("Has shape:",c_vector.shape)

The list: [1, 2]
Has length: 2
The vector: [1 2]
Has shape: (2,)


In [4]:
z = [5,6]
print("This is a list, not an array:",z)
print(type(z))

This is a list, not an array: [5, 6]
<class 'list'>


In [5]:
zarray = np.array(z)
print("This is an array, not a list",zarray)
print(type(zarray))

This is an array, not a list [5 6]
<class 'numpy.ndarray'>


#### Матрицы

In [6]:
b = list(zip(z,c_vector))
print(b)
print("Note that the length of our zipped list is 2 not (2 by 2):",len(b))

[(5, 1), (6, 2)]
Note that the length of our zipped list is 2 not (2 by 2): 2


In [7]:
print("But we can convert the list to a matrix like this:")
A = np.array(b)
print(A)
print(type(A))
print("A has shape:",A.shape)

But we can convert the list to a matrix like this:
[[5 1]
 [6 2]]
<class 'numpy.ndarray'>
A has shape: (2, 2)


## Операции с матрицами

### Сложение / вычитание скалярной величины (числа)

Рассмотрим пример для размерности $2 \times 2$, где количество строк $\times$ количество колонок.

$A$=$\bigl( \begin{smallmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{smallmatrix} \bigr)$.

Скаляром обозначим $S$.
$$
\begin{equation}
	A+S=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}+S
	=\begin{bmatrix}
	  a_{11}+S & a_{12}+S \\
	  a_{21}+S & a_{22}+S 	
	\end{bmatrix}
\end{equation}
$$

Аналогично: 

$$
\begin{equation}
	A-S=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}-S
	=\begin{bmatrix}
	  a_{11}-S & a_{12}-S \\
	  a_{21}-S & a_{22}-S 	
	\end{bmatrix}
\end{equation}
$$


Это правило работает для любой размерности.

In [8]:
print('A:\n', A, '\n')

result = A + 3
#or
result = 3 + A
print('result:\n', result)

A:
 [[5 1]
 [6 2]] 

result:
 [[8 4]
 [9 5]]


### Сложение и вычитание матриц

$A$=$\bigl( \begin{smallmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{smallmatrix} \bigr)$

$B$=$\bigl( \begin{smallmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{smallmatrix} \bigr)$.

\begin{equation}
	A -B =
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix} -
	\begin{bmatrix} b_{11} & b_{12} \\
	  b_{21} & b_{22}
	\end{bmatrix}
	=
	\begin{bmatrix}
	  a_{11}-b_{11} & a_{12}-b_{12} \\
	  a_{21}-b_{21} & a_{22}-b_{22} 	
	\end{bmatrix}
\end{equation}

Аналогично:

\begin{equation}
	A + B =
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix} +
	\begin{bmatrix} b_{11} & b_{12} \\
	  b_{21} & b_{22}
	\end{bmatrix}
	=
	\begin{bmatrix}
	  a_{11}+b_{11} & a_{12}+b_{12} \\
	  a_{21}+b_{21} & a_{22}+b_{22} 	
	\end{bmatrix}
\end{equation}


Важно помнить, что при сложении / вычитании размерность матриц должна быть одинаковой и не изменяется.

\begin{equation}
A_{2 \times 2} + B_{2 \times 2}= \begin{bmatrix}
  a_{11}+b_{11} & a_{12}+b_{12} \\
  a_{21}+b_{21} & a_{22}+b_{22} 	
\end{bmatrix}_{2 \times 2}
\end{equation}

In [9]:
B = np.random.randn(2,2)
print(A)
print(B)

[[5 1]
 [6 2]]
[[0.9043308  0.39875921]
 [0.24083564 1.66295932]]


In [10]:
result = A + B
result

array([[5.9043308 , 1.39875921],
       [6.24083564, 3.66295932]])

## Умножение матриц

### Умножение матриц на скаляр (число)

$A$=$\bigl( \begin{smallmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{smallmatrix} \bigr)$.
Обозначим скаляром $S$

\begin{equation}
	S \times A = S \times \begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}
	=
	\begin{bmatrix}
	  Sa_{11} & Sa_{12} \\
	  Sa_{21} & Sa_{22} 	
	\end{bmatrix}
\end{equation}

$3 \times A$=$A \times 3$


In [11]:
A * 3

array([[15,  3],
       [18,  6]])

### Умножение матриц

$2 \times 1$ вектор $C=\bigl( \begin{smallmatrix} c_{11} \\
  c_{21}
\end{smallmatrix} \bigr)$  

Умножим матрицу $A_{2 \times 2}$ и вектор $C_{2 \times 1}$. 
В данном случае обязательно должны совпадать размерности row (левой) **and** column (правой).


\begin{equation}
	A_{2 \times 2} \times C_{2 \times 1} = 
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}_{2 \times 2}
    \times
    \begin{bmatrix}
	c_{11} \\
	c_{21}
	\end{bmatrix}_{2 \times 1}
	=
	\begin{bmatrix}
	  a_{11}c_{11} + a_{12}c_{21} \\
	  a_{21}c_{11} + a_{22}c_{21} 	
	\end{bmatrix}_{2 \times 1}
\end{equation}

Матрица C с размерностями $2 \times 3$ и матрица A с размерностями $3 \times 2$

\begin{equation}
	A_{3 \times 2}=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} \\
	  a_{31} & a_{32} 	
	\end{bmatrix}_{3 \times 2}
	,
	C_{2 \times 3} = 
	\begin{bmatrix}
		  c_{11} & c_{12} & c_{13} \\
		  c_{21} & c_{22} & c_{23} \\
	\end{bmatrix}_{2 \times 3}
	\end{equation}

A $\times$ C будет

\begin{align}
	A_{3 \times 2} \times C_{2 \times 3}=&
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} \\
	  a_{31} & a_{32} 	
	\end{bmatrix}_{3 \times 2}
	\times
	\begin{bmatrix}
	  c_{11} & c_{12} & c_{13} \\
	  c_{21} & c_{22} & c_{23} 
	\end{bmatrix}_{2 \times 3} \\
	=&
	\begin{bmatrix}
	  a_{11} c_{11}+a_{12} c_{21} & a_{11} c_{12}+a_{12} c_{22} & a_{11} c_{13}+a_{12} c_{23} \\
	  a_{21} c_{11}+a_{22} c_{21} & a_{21} c_{12}+a_{22} c_{22} & a_{21} c_{13}+a_{22} c_{23} \\
	  a_{31} c_{11}+a_{32} c_{21} & a_{31} c_{12}+a_{32} c_{22} & a_{31} c_{13}+a_{32} c_{23}
	\end{bmatrix}_{3 \times 3}	
\end{align}

$X_{r_x \times c_x} \times Y_{r_y \times c_y}$

Важно:

* $c_x=r_y$, columns первого операнда дожны быть равны rows второго операнда.
* Размерность результата будет равна $r_x \times c_y$ (rows первого операнда и columns второго операнда).

Следовательно, $X \times Y = Y \times X$ истинно **НЕ** во всех случаях.

[Wiki Matrix multiplication](http://en.wikipedia.org/wiki/Matrix_multiplication)

In [12]:
# Let's redefine A and C to demonstrate matrix multiplication:
A = np.arange(6).reshape((3,2))
C = np.random.randn(2,2)

print(A.shape)
print(C.shape)

(3, 2)
(2, 2)


Это также называется Скалярное произведение матриц (`dot`):

In [13]:
print(A.dot(C))
print(np.dot(A,C))

[[0.27289389 0.72653593]
 [4.10199204 4.20022434]
 [7.93109019 7.67391275]]
[[0.27289389 0.72653593]
 [4.10199204 4.20022434]
 [7.93109019 7.67391275]]


А так не сработает из-за размерностей:

In [14]:
C.dot(A)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

## Обратная матрица

Матрица $2 \times 2$ $A$=$\bigl( \begin{smallmatrix} a_{11} & a_{12} \\ a_{21} & a_{22}\end{smallmatrix} \bigr)$.
Обозначим обратную матрицу для $A$ как $A^{-1}$)

$$
\begin{equation}
	A^{-1}=\begin{bmatrix}
             a_{11} & a_{12} \\
		     a_{21} & a_{22} 
           \end{bmatrix}^{-1}=\frac{1}{a_{11}a_{22}-a_{12}a_{21}}	\begin{bmatrix}
		             a_{22} & -a_{12} \\
				     -a_{21} & a_{11} 
		           \end{bmatrix}
\end{equation}
$$

Обратная матрица $A^{-1}$ имеет полезное свойсво:
$$
\begin{equation}
	A \times A^{-1}=A^{-1} \times A=I
\end{equation}
$$

где I, единичная матрица (как скалярная 1)

$$
\begin{equation}
	I_{2 \times 2}=\begin{bmatrix}
             1 & 0 \\
		     0 & 1 
           \end{bmatrix}
\end{equation}
$$
более того, $A \times I = A$ и $I \times A = A$.

[Wiki Matrix inversion](http://en.wikipedia.org/wiki/Matrix_inversion)

In [ ]:
# note, we need a square matrix (# rows = # cols), use C:
C_inverse = np.linalg.inv(C)
print(C_inverse)

Check that $C\times C^{-1} = I$:

In [ ]:
print(C.dot(C_inverse))
print("Is identical to:")
print(C_inverse.dot(C))

## Транспонирование матриц

$$
\begin{equation}
	A_{3 \times 2}=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} \\
	  a_{31} & a_{32} 	
	\end{bmatrix}_{3 \times 2}	
\end{equation}
$$
Транспонированная матрица A (обозначается как $A^{\prime}$)
$$
\begin{equation}
   A^{\prime}=\begin{bmatrix}
	  a_{11} & a_{21} & a_{31} \\
	  a_{12} & a_{22} & a_{32} \\
	\end{bmatrix}_{2 \times 3}
\end{equation}
$$

In [ ]:
A = np.arange(6).reshape((3,2))
B = np.arange(8).reshape((2,4))
print("A is")
print(A)

print("The Transpose of A is")
print(A.T)

Матрица A размерности $N \times M$ и B размерности $M \times P$
$$
\begin{equation}
	(AB)^{\prime}=B^{\prime}A^{\prime}
\end{equation}
$$

[Wiki Matrix transposition](http://en.wikipedia.org/wiki/Matrix_transposition)

In [ ]:
print(B.T.dot(A.T))
print("Is identical to:")
print((A.dot(B)).T)